### ISSUE TITLE
A question about metrics.py

### ISSUE THREAD

**Issue by huangyuan2020** [alibaba/UniFuse-Unidirectional-Fusion#10]
Thank you very much for your work, but there is a piece of code that makes me a little confused. 
The location is Line18-Line21 in [metrics.py](https://github.com/alibaba/UniFuse-Unidirectional-Fusion/blob/main/UniFuse/metrics.py) 
I understand that it means that gt and pred are limited to the range of 0.1-10 before calculating the evaluation metrics. However, the logic of these four lines only limits gt to 0.1 to 10, while pred will have an area greater than 0.1. 
I hope you can remove my confusion.

**Comment by hualie** [comment]
Thanks for pointing this out. In fact, line 21 should be _pred[pred>10] = 10_. But both versions perform the same, as we have limited the estimated depth range within [0, 10] (https://github.com/alibaba/UniFuse-Unidirectional-Fusion/blob/5da3a4e64491c3efff3ce8613ba289147515c832/UniFuse/networks/unifuse.py#L174).

**Comment by HalleyJiang** [comment]
Thanks for pointing this out. In fact, line 21 should be _pred[pred>10] = 10_. 
But both versions perform the same, as we have limited the estimated depth range within [0, 10] (https://github.com/alibaba/UniFuse-Unidirectional-Fusion/blob/5da3a4e64491c3efff3ce8613ba289147515c832/UniFuse/networks/unifuse.py#L174).

**Comment by huangyuan2020** [comment]
Ok, I see. Thank you for your reply.
