### ISSUE TITLE
Is there anything about Matterport Preprocessing

### ISSUE THREAD

**Issue by chenerg** [alibaba/UniFuse-Unidirectional-Fusion#2]
> Download PanoBasic
> 
> Copy stitching_Matterport3D.m to PanoBasic
> 
> Modify the directories in stitching_Matterport3D.m, i.e., changing source_dir to the folder of Matterport3D and changing target_dir as the output folder of panorama images and depth maps.
> 
> Execute stitching_Matterport3D.m using Matlab.

It seems that stiching_Matterport3D uses `stich.m`, while `stich.m` is missing in PanoBasic.

@robertsheng

**Comment by HalleyJiang** [comment]
Please download the code of Matterport3D pre-processing again. I missed some .m files for the first time. We have added them now.

**Comment by chenerg** [comment]
Do you mean that I should copy `stich.m` to PanoBasic? I'm confused about how `PanoBasic` and `stitching_Matterport3D.m` work together,  which is shown in https://github.com/alibaba/UniFuse-Unidirectional-Fusion/blob/fece286301838efef7967d7030ab449e8ea0e449/UniFuse/Matterport3D/README.md.

**Comment by HalleyJiang** [comment]
You should copy all the .m files under the folder Matterport3D to PanoBasic. stitching_Matterport3D.m has to call other .m files by us. The README.md has not been updated yet, although we had added these .m files several days ago.

**Comment by chenerg** [comment]
That's great!

**Comment by chenerg** [comment]
Sorry to bother you again. It seems that you have changed the `combineViews.m` in PnnoBasic, would you please share the code?

**Comment by HalleyJiang** [comment]
We have updated the code for pre-processing Matterport3D. Please try again according to readme.
