### ISSUE TITLE
 How to get the 3d60 train data set

### ISSUE THREAD

**Issue by kongweifeng678** [alibaba/UniFuse-Unidirectional-Fusion#3]
When I use 3d60（Left/Down）to  evaluate, it's OK, but some data will be missing during training.
![微信图片_20210605143613](https://user-images.githubusercontent.com/61935655/120882619-957eff00-c60b-11eb-8c5b-9ea82d476ec7.png)

**Comment by HalleyJiang** [comment]
Some training samples may be missed in your downloading files. There are many missing several samples. Please remove them on our providing training file list.

**Comment by HalleyJiang** [comment]
According to our experience, the missing samples come from the real datasets, Matterport3D and Stanford2D3D. These missing samples can be found at the [**Real Domain Only Version**](https://zenodo.org/record/3492155#.XagQA-gzaUk) provided 3D60. If you want to train the complete training set. You should download the **Read Domain Only Version** and overwrite the original dataset with it.

**Comment by kongweifeng678** [comment]
Thank you very much!
